version: '3.5'

services:
  php:
    build:
      context: .
      target: dev
    user: fig
    volumes:
    - .:/fig-website
    working_dir: /fig-website
    command:
      - 'sculpin'
      - 'generate'
      - '--watch'
      - '--server'
    ports:
      - 8000:8000

  html-proofer:
    image: 18fgsa/html-proofer
    working_dir: /fig-website
    volumes:
      - .:/fig-website

  dart-sass:
    image: michalklempa/dart-sass:latest
    user: 1000:1000
    working_dir: /fig-website
    volumes:
      - .:/fig-website
    command: 
      - '/opt/dart-sass/sass'
      - 'source/_sass/all.scss:output_dev/css/all.css'
      - '--style=compressed'
      - '--color'
