sculpin_content_types:
  posts:
    singular_name: post
    type: path
    path: _posts
    permalink: blog/:year/:month/:slug_title
    taxonomies:
      - tags
      - categories
  pages:
    singular_name: page
    permalink: :basename
    type: path
    path: _pages
  authors:
    singular_name: author
    permalink: authors/:basename
    type: path
    path: _authors
  psr:
    permalink: psr/:basename
    type: path
    path: _psr
  bylaws:
    singular_name: bylaw
    permalink: bylaws/:slug_title
    type: path
    path: _bylaws

sculpin:
  ignore: ["**/*.scss"]

services:
  fig.website.link_processor_extension:
    class: Fig\Website\TwigLinkProcessor
    tags:
      - { name: twig.extension }

  aptoma.twig.markdown_extension:
    class: Aptoma\Twig\Extension\MarkdownExtension
    arguments:
      $markdownEngine: '@Fig\Website\NullSafeCommonMarkEngine'
    tags:
      - { name: twig.extension }

  Fig\Website\NullSafeCommonMarkEngine:
    arguments:
      - '@Aptoma\Twig\Extension\MarkdownEngine\PHPLeagueCommonMarkEngine'

  Aptoma\Twig\Extension\MarkdownEngine\PHPLeagueCommonMarkEngine:
    arguments:
      - '@League\CommonMark\GithubFlavoredMarkdownConverter'

  League\CommonMark\GithubFlavoredMarkdownConverter:
    arguments:
      - []
      - '@League\CommonMark\ConfigurableEnvironmentInterface'

  League\CommonMark\ConfigurableEnvironmentInterface:
    factory: ['League\CommonMark\Environment', 'createCommonMarkEnvironment']
    calls:
      - ['addExtension', ['@League\CommonMark\Extension\Table\TableExtension']]
      - ['addBlockRenderer', ['League\CommonMark\Block\Element\FencedCode', '@Spatie\CommonMarkHighlighter\FencedCodeRenderer']]
      - ['addBlockRenderer', ['League\CommonMark\Block\Element\IndentedCode', '@Spatie\CommonMarkHighlighter\IndentedCodeRenderer']]

  League\CommonMark\Extension\Table\TableExtension: ~

  Spatie\CommonMarkHighlighter\FencedCodeRenderer:
    arguments:
      - ['php']
  Spatie\CommonMarkHighlighter\IndentedCodeRenderer:
    arguments:
      - ['php']
