https://{default}/:
  type: upstream
  upstream: php-fig-website:http
  cache:
    enabled: true

https://www.{default}/:
  type: redirect
  to: https://{default}/

http://www.{default}/:
  type: redirect
  to: https://{default}/

http://{default}/:
  type: redirect
  to: https://{default}/
